- scripts/create-release.sh
- scripts/get-latest-version.sh
* Fixing default value for version
* Fixing wrong output directory
> Fixing output-directory and default value

- .circleci/config.yml
- README.md
- gulpfile.js
- package.json
- src/qlik-multi-kpi.qext
[QPE-111] Cleaning up build script to be more obvious
[QPE-111] Removing empty fields in .qext-file to enable viz-bundle build to succeed
> QPE-111 Cleaning up build script

- LICENSE
> [QPE-147] Adding MIT license file

- src/component.js
- src/definition.js
- src/qlik-multi-kpi.less
These changes results in using the new style of data UI in the property panel. Please make sure the sub-properties for the measure still and that the limitations in number of dims/meas works as expected.
> Update extension definition for data

- src/component.js
- src/paint.js
- src/statisticBlock.js
link to Jira ticket 
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-168
> QPE-[168] deleteing a KPI deletes all its instances

- src/component.js
- src/definition.js
- src/qlik-multi-kpi.less
Jira ticket: 
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-154
> icons alignment

- src/qlik-multi-kpi.less
- src/statisticBlock.js
hiehgt of cards/segments container set to 100%
to prevent copping its top edge
Jira ticket link 
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-165
> [QPE-165] scrolling disabled in edit mode

- src/dimensionEntry.js
- src/statisticBlock.js
jira ticket link
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-170
> [QPE-170] dimension doesn't respond when clikced on null values

- src/dimensionEntry.js
- src/qlik-multi-kpi.less
- Fix edge and IE layout bug
- Card headers are not clickable in editmode
> Bug QPE-265

- gulpfile.js
- settings.js
- src/qlik-multi-kpi.less
JIRA ticket
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-345
> [QPE-345] Dimension selectors disappear when window is reduced in height

- src/component.js
- src/paint.js
JIRA ticket Link
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-269
> QPE-269 undo/redo bug fixed

- src/qlik-multi-kpi.less
- src/statisticBlock.js
JIRA ticket
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-384
> [QPE-384] setting a min-width for IE

- .eslintrc.js
- src/ValueComponent.js
- src/options.js
- webpack.config.js
JIRA ticket
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-385
> [QPE-385] resposiveness 

- src/ValueComponent.js
JIRA ticket link
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-430
> [QPE-430] master viz interaction disable,, console error removed

- src/definition.js
- src/options.js
- src/qlik-multi-kpi.less
- src/statisticBlock.js
- src/statisticItem.js
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-385
> work around in responsiveness

- src/definition.js
- src/statisticBlock.js
- now if you change the size on measure the size of the values should change as well
https://tretton37.atlassian.net/browse/QPE-559
> Fixed size changing on measures

- src/qlik-multi-kpi.less
- src/statisticItem.js
More responsive layout
https://tretton37.atlassian.net/browse/QPE-560
Before
---
After
---
> [QPE 560] Fixed segment layout

- src/qlik-multi-kpi.less
https://tretton37.atlassian.net/browse/QPE-572
> [QPE-572] Mobile layout adjustments

- src/ValueComponent.js
- src/component.js
- src/dimensionEntry.js
- src/statisticBlock.js
JIRA ticket
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-568
> snapshot enabled for KPI

- .circleci/config.yml
- src/dimensionEntry.js
- src/qlik-multi-kpi.less
- src/statisticBlock.js
- src/statisticItem.js
JIRA ticket
https://tretton37.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=QPE&modal=detail&selectedIssue=QPE-573
> [QPE-573] infographic icons responsiveness

- settings.js
- src/qlik-multi-kpi.less
https://tretton37.atlassian.net/browse/QPE-590
Note that I am waiting on @Caele's input if this is even a solution, do not merge before we get approval
> QPE 590 Fixed horizontal layout

- src/ValueComponent.js
-Enables interaction and fixes layout issues that appear
when opening the selection menu of the master object.
Issue: QLIK-96142
> Select values from the Master objects

- src/definition.js
- src/options.js
- src/qlik-multi-kpi.less
- src/statisticBlock.js
- src/statisticItem.js
-Distribute content evenly and aligned.
-Make sure no content overlaps other content.
Issue: QLIK-92427
> Improve and enforce space distribution

- src/definition.js
- src/statisticBlock.js
-This is mimicking the behavior of the native kpi,
not the solution of the original multi kpi.
Issue: QLIK-96228
> Possibility to use conditional color of measure

- src/qlik-multi-kpi.less
> changes for defect QB - 216 (Icon size)

- src/component.js
**Bug:** 
QB-459 (https://jira.qlikdev.com/browse/QB-459?filter=-1)
**Issue:**
Unable export multi KPI into PDF - Qlik Sense Desktop
**Fix:**
Now users will be able to export multi KPI into PDF - Qlik Sense Desktop
**Files updated:**
component.js  file got updated with the object key value to true, export: true
support: {
snapshot: true,
export: true,
exportData: true
},
> Fix: QB-459-Unable-to-pdfExport-in-multiKPI

- src/numberFormatter.js
QB-271-numerical-abbreviation bug
> Qb 271 numerical abbreviation

- src/definition.js
This PR is regarding bug QB-295, Unexpected icons for measure Alignment in Multi KPI.
Changes are made in file definition.js under src folder.
> fix:alignment icons fixed

- .gitignore
- src/ValueComponent.js
Re-rendering of value component's children of non embedded item was not happening if there are any embedded item present.
> QB-268 Calculations not updating

- src/qlik-multi-kpi.less
> fix: make sure the width of card is correct

- .circleci/config.yml
- src/definitionComponents.js
Mostly prettier changes. Real changes are here:
https://github.com/qlik-oss/qsSimpleKPI/pull/107/files?diff=split&w=1#diff-c692b18c3cfdb36adf36f3a672d2650e5020fe52e455471e1dd232aff44ec2abR106
https://github.com/qlik-oss/qsSimpleKPI/pull/107/files?diff=split&w=1#diff-c692b18c3cfdb36adf36f3a672d2650e5020fe52e455471e1dd232aff44ec2abR132-R137
> fix: only save on blur textarea
